/**
 * MCP tools: resolve_component_deps, install_components
 *
 * Uses the dependency graph from scripts/dep-graph.json to resolve
 * transitive dependencies and generate install commands.
 */
import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/** Block type → Maranello component slug mapping */
export const BLOCK_TO_COMPONENT: Record<string, string> = {
  "gauge-block": "mn-gauge",
  "chart-block": "mn-chart",
  "gantt-block": "mn-gantt",
  "kanban-block": "mn-kanban-board",
  "funnel-block": "mn-funnel",
  "hbar-block": "mn-hbar",
  "speedometer-block": "mn-speedometer",
  "map-block": "mn-map",
  "okr-block": "mn-okr",
  "system-status-block": "mn-system-status",
  "data-table-maranello": "mn-data-table",
  "workflow-orchestrator-block": "mn-workflow-orchestrator",
};

/** Load the dependency graph (generated by scripts/sync-registry-deps.ts) */
function loadDepGraph(): Record<string, string[]> {
  try {
    const graphPath = join(process.cwd(), "scripts", "dep-graph.json");
    return JSON.parse(readFileSync(graphPath, "utf-8"));
  } catch {
    return {};
  }
}

/** Resolve transitive dependencies for a list of component slugs */
export function resolveComponentDeps(slugs: string[]): string[] {
  const graph = loadDepGraph();
  const resolved = new Set<string>();

  function walk(slug: string) {
    if (resolved.has(slug)) return;
    resolved.add(slug);
    const deps = graph[slug] ?? [];
    for (const dep of deps) walk(dep);
  }

  for (const slug of slugs) walk(slug);
  return [...resolved].sort();
}

export function registerDepsTools(server: McpServer): void {
  server.tool(
    "resolve_component_deps",
    "Given a list of Maranello component slugs, return the full transitive dependency closure",
    {
      components: z.array(z.string()).describe("List of component slugs (e.g. mn-gauge, mn-data-table)"),
    },
    async ({ components }) => {
      const resolved = resolveComponentDeps(components);
      const graph = loadDepGraph();

      const details = resolved.map((slug) => ({
        slug,
        dependencies: graph[slug] ?? [],
        requested: components.includes(slug),
      }));

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({ requested: components, resolved, details }, null, 2),
        }],
      };
    },
  );

  server.tool(
    "install_components",
    "Generate the shadcn install command for a list of components with resolved dependencies",
    {
      components: z.array(z.string()).describe("Component slugs to install"),
      registry_url: z.string().optional().describe("Registry URL (default: local)"),
    },
    async ({ components, registry_url }) => {
      const resolved = resolveComponentDeps(components);
      const url = registry_url ?? "https://convergio-ui-framework.vercel.app/r";

      const command = resolved.length > 0
        ? `npx shadcn add ${resolved.join(" ")} --registry ${url}`
        : "No components to install.";

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            requested: components,
            installing: resolved,
            command,
          }, null, 2),
        }],
      };
    },
  );
}
