#!/usr/bin/env bash
set -euo pipefail

# Usage: ./scripts/create-component.sh MnMyComponent
# Creates src/components/maranello/mn-my-component.tsx with a standard template
# and adds a barrel export to src/components/maranello/index.ts.

trap 'echo "ERROR: Script failed at line $LINENO" >&2' EXIT

# ── Validate input ──────────────────────────────────────────────
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <MnComponentName>" >&2
  echo "Example: $0 MnMyWidget" >&2
  exit 1
fi

local_name="$1"

# Must start with Mn
if [[ ! "$local_name" =~ ^Mn[A-Z] ]]; then
  echo "ERROR: Component name must start with 'Mn' followed by uppercase (e.g. MnMyWidget)" >&2
  exit 1
fi

# ── Derive file name (PascalCase -> kebab-case) ────────────────
kebab=$(echo "$local_name" | sed 's/\([A-Z]\)/-\1/g' | sed 's/^-//' | tr '[:upper:]' '[:lower:]')
file_name="${kebab}.tsx"

# ── Paths ───────────────────────────────────────────────────────
script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
component_dir="${project_root}/src/components/maranello"
component_path="${component_dir}/${file_name}"
barrel_path="${component_dir}/index.ts"

if [[ -f "$component_path" ]]; then
  echo "ERROR: ${component_path} already exists" >&2
  exit 1
fi

# ── Derive props name ──────────────────────────────────────────
props_name="${local_name}Props"

# ── CVA variants name (camelCase) ──────────────────────────────
first_char="$(echo "$local_name" | cut -c1 | tr '[:upper:]' '[:lower:]')"
rest="$(echo "$local_name" | cut -c2-)"
variants_name="${first_char}${rest}Variants"

# ── Write component file ───────────────────────────────────────
cat > "$component_path" << TEMPLATE
"use client"

import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

// ---------------------------------------------------------------------------
// CVA variants
// ---------------------------------------------------------------------------

const ${variants_name} = cva("", {
  variants: {
    size: {
      sm: "",
      md: "",
      lg: "",
    },
  },
  defaultVariants: {
    size: "md",
  },
})

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface ${props_name}
  extends React.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof ${variants_name}> {}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * \`${local_name}\` -- TODO: describe what this component does.
 *
 * Part of the Maranello Design System.
 */
export function ${local_name}({
  size,
  className,
  ...props
}: ${props_name}) {
  return (
    <div
      {...props}
      className={cn(${variants_name}({ size }), className)}
    />
  )
}

${local_name}.displayName = "${local_name}"

export { ${variants_name} }
TEMPLATE

echo "Created: ${component_path}"

# ── Add barrel export ───────────────────────────────────────────
module_name="${kebab}"
export_line="export { ${local_name}, type ${props_name} } from \"./${module_name}\""

if grep -qF "$local_name" "$barrel_path" 2>/dev/null; then
  echo "WARN: ${local_name} already exported in index.ts, skipping barrel update" >&2
else
  echo "" >> "$barrel_path"
  echo "/* Generated by create-component.sh */" >> "$barrel_path"
  echo "${export_line}" >> "$barrel_path"
  echo "Updated: ${barrel_path}"
fi

trap - EXIT
echo "Done. Edit ${component_path} to implement your component."
